development:
  adapter: postgresql
  encoding: unicode
  database: InfoBytes_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: InfoBytes_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: InfoBytes_production
  pool: 5
